language: php
php:
- hhvm

before_install:
- echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc

before_script:
- gem install sass
- composer selfupdate
- composer install

script:
- vendor/bin/bldr build publish

env:
  global:
    secure: "r59rckvqgfFUfrqEr/JOQjLAlb8x2l81bvcbNtBM5+TuAKI3mEAOsHmXcPmcJTHdsKquGNi9HrVzL1m2DyNHcIEd4Pgmh8Pjy6mr1F4D55r8rW7IyPgvjii/7TWLElGEBIMtP7O5tup9vb7hMTazxmQcrxBT3qRuHAPkdphXnfs="
