language: php
php: 7

sudo: true

branches:
  only:
    - source

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc

install:
  - gem install sass
  - composer install --prefer-dist
  - sudo pip install Pygments
  - sudo python setup.py install

script: sh build.sh

after_success: if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh publish.sh; fi

env:
  global:
    secure: "sciTyc7ftMc+ZDHWPFTZrwd4d9CDsIp0O5rMiKzdyNLgBk8yqNq6FReb5UaDz4YuF51hxYVt5vrZNi7aGSjtikXe4AdSB7EQe5o9PK/oN45R0WUe5gOgC4i+KrZPcCEd7ZM82WZlQgWI20oI17dBHlfMw38SG/SqNfhG5cKLOKk="
