---
name: Publish to GitHub Pages

on:
  push:
    branches: source

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: .shiki-cache
          key: ${{ runner.os }}-shiki

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn install

      - name: Build
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          cname: wouterj.nl
          publish_branch: master
